version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=traindb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  spark_client:
    build:
      context: .
      dockerfile: Dockerfile.spark_client
    container_name: spark_client
    volumes:
      - ./scripts:/scripts  
    # - shared_scripts:/scripts
    ports:
      - "2222:22"

  airflow-webserver:
    image: apache/airflow:2.7.1
    command: webserver
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres/traindb
      - AIRFLOW__WEBSERVER__SECRET_KEY=bunumecburenekledim_123
    volumes:
      - shared_dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.7.1
    command: scheduler
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password@postgres/traindb
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags/current/dags
      - AIRFLOW__WEBSERVER__SECRET_KEY=bunumecburenekledim_123
    volumes:
      - shared_dags:/opt/airflow/dags

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.2.1
    user: "50000:0" # Airflow kullanıcısı ile eşleştiriyoruz (İzin hatası almamak için)
    environment:
      - GITSYNC_REPO=https://github.com/Burcuque/dataops-assignment.git
      - GITSYNC_REF=main
      - GITSYNC_PERIOD=30s
      - GITSYNC_ROOT=/opt/airflow/dags # İndirme yeri Airflow ile aynı olmalı
      - GITSYNC_DEST=repo
      - GITSYNC_LINK=current
    volumes:
      - shared_dags:/opt/airflow/dags

volumes:
  shared_dags:
  shared_scripts:
