FROM python:3.9-slim

# SSH Server kurulumu
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
# Şifre belirle (Test için kolaylık: root/root)
RUN echo 'root:root' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Gerekli kütüphaneler
RUN pip install pandas sqlalchemy psycopg2-binary boto3

# Uygulama klasörü
WORKDIR /scripts

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
